spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:todo}"
    username: ${DB_USER:todo}
    password: ${DB_PASS:todo}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true