spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/todo"
    username: todo
    password: todo
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true