version: '3.9'

networks:
  todo:
    name: todo

services:
  database:
    hostname: db
    container_name: todo_db
    image: postgres:13.9-alpine
    restart: always
    environment:
      POSTGRES_USER: "todo"
      POSTGRES_PASSWORD: "todo"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER" ]
      interval: 1s
      timeout: 1s
      retries: 20
    networks:
      - todo
