version: '3.9'

services:
  database:
    container_name: postgres_todo
    image: postgres:13.8-alpine
    environment:
      POSTGRES_USER: "todo"
      POSTGRES_PASSWORD: "todo"
    ports:
      - "5432:5432"
